### ISSUE TITLE
Gambar Untuk Wiki/Panduan

### ISSUE THREAD

**Issue by afa28** [OpenSID/OpenSID#4080]
![sdgs-1](https://user-images.githubusercontent.com/249563/118609247-e74b1b00-b7fd-11eb-89d2-b840ca87d02e.jpg)
![sdgs-2](https://user-images.githubusercontent.com/249563/118609265-ec0fcf00-b7fd-11eb-940d-fc261f3110ae.jpg)
![sdgs-3](https://user-images.githubusercontent.com/249563/118609273-ed40fc00-b7fd-11eb-83ca-bcc7b508f315.jpg)
![sdgs-4](https://user-images.githubusercontent.com/249563/118609274-edd99280-b7fd-11eb-88b1-c094816fc21f.jpg)
![sdgs-5](https://user-images.githubusercontent.com/249563/118609277-edd99280-b7fd-11eb-8ec0-92f57553ac6c.jpg)

![anjungan-1](https://user-images.githubusercontent.com/249563/117870791-e8e98000-b2df-11eb-8fb6-9ec562c16af9.jpg)

Modul
![server-publik-1](https://user-images.githubusercontent.com/249563/114012282-7c76fd80-98a9-11eb-827e-27a8eca7834e.jpg)
![server-publik-2](https://user-images.githubusercontent.com/249563/114012298-80a31b00-98a9-11eb-8272-1196ce9e1902.jpg)
![server-publik-3](https://user-images.githubusercontent.com/249563/114012302-81d44800-98a9-11eb-8eaa-ecda42f23681.jpg)
![server-publik-4](https://user-images.githubusercontent.com/249563/114012304-826cde80-98a9-11eb-9cdb-0e3f0423efdc.jpg)

Pelanggan:
![pelanggan](https://user-images.githubusercontent.com/57283157/111893027-81772880-8a32-11eb-8753-0011e94977a8.png)
![pelanggan-1](https://user-images.githubusercontent.com/57283157/111893028-82a85580-8a32-11eb-9f94-70559389c3d2.png)
![pelanggan-3](https://user-images.githubusercontent.com/57283157/111893939-2bf24a00-8a39-11eb-8fb7-9374afe8cc3b.png)
![pelanggan-3](https://user-images.githubusercontent.com/57283157/111894077-68727580-8a3a-11eb-85af-ea582056ebdd.png)

**Comment by afa28** [comment]
Suplemen:
![suplemen](https://user-images.githubusercontent.com/57283157/111893064-bdaa8900-8a32-11eb-993c-ff20f67608a2.png)

**Comment by afa28** [comment]
Pembaca QR Code:
![scan qrcode](https://user-images.githubusercontent.com/57283157/111893275-365e1500-8a34-11eb-83f1-e4139e7f9741.png)

**Comment by afa28** [comment]
Pengaturan Surat QR Code
![pengaturan-surat-qrcode](https://user-images.githubusercontent.com/57283157/111893333-9d7bc980-8a34-11eb-8728-8de4de761084.png)

**Comment by afa28** [comment]
Login Layanan Mandiri Login :
![layanan-mandiri-login-1](https://user-images.githubusercontent.com/57283157/111893381-f77c8f00-8a34-11eb-85db-b1e00436f7b4.png)
![layanan-mandiri-login-2](https://user-images.githubusercontent.com/57283157/111893382-f9465280-8a34-11eb-9cfa-edcd13de73f9.png)

**Comment by afa28** [comment]
Panduan : 
- [ ] 1. #4040: Petugas yang pertama kali memasukkan data penduduk kembali ditampilkan. [bug-fix]
- [ ] 2. #4041: Penambahan KK dan anggota keluarga baru sekarang normal kembali. [bug-fix]
- [ ] 3. Tidak tampilkan kolom isian Tanggal Lapor di form ubah biodata penduduk. [bug-fix]
- [ ] 4. Statistik > Laporan Bulanan di baris Kelahiran/Keluarga Baru sekarang dibatasi melaporkan keluarga baru yg dibentuk dari penduduk yang ada (mis. setelah pecah keluarga). [bug-fix]
- [ ] 5. #3962: Sekarang bisa sisipkan QRCode di layanan surat berisi tautan untuk verifikasi keabsahan surat.
- [ ] 6. #4036: Tampilkan notifikasi masa berlangganan layanan OpenDesa di header Admin.
- [ ] 7. #790: Sediakan fitur impor/ekspor Data Suplemen.
- [ ] 8. #4058: Sediakan fitur untuk membaca QR Code dari file atau dari kamera perangkat.
- [ ] 9. #4057: Gunakan scan e-KTP untuk login layanan mandiri, cari penduduk dan pilih penduduk di form surat.
- [ ] 10. Tutup celah SQL injection di tampilan analisis di Web. [security-fix]

**Comment by afa28** [comment]
Layanan Mandiri > Permohonan Surat : 
![permohonan-surat-1](https://user-images.githubusercontent.com/57283157/112781120-6c267d80-9074-11eb-8934-aed6e520a5ee.png)

**Comment by afa28** [comment]
**Premium - perbaikan bug:**
- [ ] 1. #4040: Petugas yang pertama kali memasukkan data penduduk kembali ditampilkan. [bug-fix]
- [ ] 2. #4041: Penambahan KK dan anggota keluarga baru sekarang normal kembali. [bug-fix]
- [ ] 3. Tidak tampilkan kolom isian Tanggal Lapor di form ubah biodata penduduk. [bug-fix]
- [ ] 4. Statistik > Laporan Bulanan di baris Kelahiran/Keluarga Baru sekarang dibatasi melaporkan keluarga baru yg dibentuk dari penduduk yang ada (mis. setelah pecah keluarga). [bug-fix]
- [ ] 5. Tutup celah SQL injection di tampilan analisis di Web. [security-fix]
- [ ] 6. #4078: Sekarang pilihan layanan mandiri di form pengaturan surat baru tersimpan benar. [bug-fix]
- [ ] 7. #4069: Perbaiki tampilkan data wilayah di laporan cetak Data Kependudukan Wilayah. [bug-fix]
- [ ] 8. Tutup celah pengguna layanan mandiri bisa lihat dokumen penduduk lain. [security-fix]
- [ ] 9. #4062: Sekarang jumlah peserta di statistik program bantuan tampil benar untuk kasus di mana ada penduduk yang kolom lokasi tempat tinggal kosong. [bug-fix]
- [ ] 10. #4087: Sekarang di laporan cetak statistik kependudukan, penandatangan tampil benar untuk kasus di mana perangkat desa yg dipilih sebelumnya diubah di Pemerintahan Desa dari Tidak Terdata menjadi Dari Database Penduduk. [bug-fix]
- [ ] 11. #4020: Sekarang di form Pembangunan lokasi menampilkan semua wilayah, termasuk dusun yg tidak ada RW atau RT. [bug-fix]
- [ ] 12. #4081: Sekarang penandatangan laporan cetak inventaris sesuai dengan yang dipilih. [bug-fix]
- [ ] 13. #4092: Sekarang di form Persil lokasi menampilkan semua wilayah, termasuk dusun yg tidak ada RW atau RT. [bug-fix]
- [ ] 14. #4088: Perbaiki alur permohonan surat layanan mandiri supaya membatasi akses menu sesuai status permohonan. [security-fix]
- [ ] 15. #4096: Perbaiki dan perjelas alur pengelolaan permohonan surat layanan mandiri di modul Admin supaya membatasi akses menu sesuai status permohonan. [bug-fix]
- [ ] 16. #4084: Perbaiki urutan Rumah Tangga. [bug-fix]
- [ ] 17. #3356: Sekarang tidak bisa lagi memasukkan peserta duplikat ke program bantuan. [bug-fix]

**Premium - penambahan fitur:**
- [ ] 1. #3962: Sekarang bisa sisipkan QRCode di layanan surat berisi tautan untuk verifikasi keabsahan surat.
- [ ] 2. #4036: Tampilkan notifikasi masa berlangganan layanan OpenDesa di header Admin.
- [ ] 3. #790: Sediakan fitur impor/ekspor Data Suplemen.
- [ ] 4. #4058: Sediakan fitur untuk membaca QR Code dari file atau dari kamera perangkat.
- [ ] 5. #4057: Gunakan scan e-KTP untuk login layanan mandiri, cari penduduk dan pilih penduduk di form surat.
- [ ] 6. #4029: Tampilkan batas ukuran unggahan dokumen kelengkapan penduduk di Layanan Mandiri dan menu Penduduk.
- [ ] 7. Pilih pamong penandatangan secara otomatis di form cetak Wilayah Administratif, Pembangunan dan Data Suplemen.
- [ ] 8. #3524: Sekarang kepala desa di Identitas Desa diambil dari pamong di Pemerintahan Desa.
- [ ] 9. #4077: Kode indikator & pertanyaan analisis sekarang bisa berisi huruf.

**Comment by afa28** [comment]
Identitas Desa : 
![identitas-desa](https://user-images.githubusercontent.com/57283157/112782012-35516700-9076-11eb-8e6d-34824c836707.png)

**Comment by afa28** [comment]
Permohonan Surat Layanan Mandiri : 
![permohonan-surat-layanan-mandiri](https://user-images.githubusercontent.com/57283157/112782149-8f522c80-9076-11eb-9e3c-47cd8ba7be45.png)
![permohonan-surat-layanan-mandiri-1](https://user-images.githubusercontent.com/57283157/112782153-9416e080-9076-11eb-871f-e8a35c6ae1e0.png)

**Comment by afa28** [comment]
QR Code Scanner : 
![qrcode scanner](https://user-images.githubusercontent.com/57283157/112782844-2ec3ef00-9078-11eb-9ee9-4cdfe14840c8.png)

**Comment by afa28** [comment]
![ekspor](https://user-images.githubusercontent.com/57283157/112783545-c1b15900-9079-11eb-82c8-cd44615e1543.png)

**Comment by afa28** [comment]
Login Layanan Mandiri, latar default : 
![layanan-mandiri](https://user-images.githubusercontent.com/57283157/112783955-ac88fa00-907a-11eb-8390-80386b3e278e.png)
![layanan-mandiri-2](https://user-images.githubusercontent.com/57283157/112783975-b14dae00-907a-11eb-8747-649513b0a473.png)

**Comment by agungsugiarto** [comment]
Panduan untuk v21.05

Premium penambahan fitur
1.  #4108 Filter Arsip Layanan Surat menurut bulan

**Comment by agungsugiarto** [comment]
#4054 - Impor data survei Google Forms ke master analisis
![image1](https://user-images.githubusercontent.com/10989147/115205820-26fde480-a124-11eb-92f7-0bee1a358729.png)

![image2](https://user-images.githubusercontent.com/10989147/115205845-2d8c5c00-a124-11eb-84c0-5ac7b8918e9c.png)

![image3](https://user-images.githubusercontent.com/10989147/115205863-311fe300-a124-11eb-900c-0415341f5485.png)

![image4](https://user-images.githubusercontent.com/10989147/115206093-7217f780-a124-11eb-8b90-4af65e520396.png)

![image5](https://user-images.githubusercontent.com/10989147/115206111-75ab7e80-a124-11eb-9a5b-617586a74d39.png)

![image6](https://user-images.githubusercontent.com/10989147/115206125-793f0580-a124-11eb-8fd1-9a8cd58bcf9f.png)

![image7](https://user-images.githubusercontent.com/10989147/115206143-7d6b2300-a124-11eb-8692-8eb8a662f7cc.png)

![image8](https://user-images.githubusercontent.com/10989147/115206158-80661380-a124-11eb-83ba-3206be0c5af7.png)

![image9](https://user-images.githubusercontent.com/10989147/115206171-83f99a80-a124-11eb-943a-63706e196586.png)

![image10](https://user-images.githubusercontent.com/10989147/115206182-86f48b00-a124-11eb-89b8-dfb8481d7930.png)

![image11](https://user-images.githubusercontent.com/10989147/115206195-89ef7b80-a124-11eb-97d8-bf1fc7a45421.png)

![image12](https://user-images.githubusercontent.com/10989147/115206205-8cea6c00-a124-11eb-8bc4-69caf5cdcf1a.png)

![image13](https://user-images.githubusercontent.com/10989147/115206212-907df300-a124-11eb-8d86-dc62b4e449f8.png)

![image14](https://user-images.githubusercontent.com/10989147/115206223-9378e380-a124-11eb-9dea-c745395b2cf8.png)

![image15](https://user-images.githubusercontent.com/10989147/115206231-9673d400-a124-11eb-956f-52516773c622.png)

![image16](https://user-images.githubusercontent.com/10989147/115206245-9a9ff180-a124-11eb-9599-ef4f5e72e2e0.png)

![image17](https://user-images.githubusercontent.com/10989147/115206256-9d024b80-a124-11eb-99d0-bfdde7a99d41.png)

![image18](https://user-images.githubusercontent.com/10989147/115206269-9f64a580-a124-11eb-9ffe-958de4f73836.png)

![image19](https://user-images.githubusercontent.com/10989147/115206278-a25f9600-a124-11eb-824f-e6a66a90b988.png)

![image20](https://user-images.githubusercontent.com/10989147/115206295-a55a8680-a124-11eb-8887-c5086c11022c.png)

![image21](https://user-images.githubusercontent.com/10989147/115206305-a986a400-a124-11eb-969b-f10e9013b590.png)

![image22](https://user-images.githubusercontent.com/10989147/115206320-ac819480-a124-11eb-98a1-a90044d13f3e.png)

![image23](https://user-images.githubusercontent.com/10989147/115206330-af7c8500-a124-11eb-9291-7f4dd21d1cf6.png)

![image24](https://user-images.githubusercontent.com/10989147/115206344-b1dedf00-a124-11eb-8325-bf7444a11636.png)

![image25](https://user-images.githubusercontent.com/10989147/115206350-b4413900-a124-11eb-8855-b23f5c4ebd29.png)

![image26](https://user-images.githubusercontent.com/10989147/115206357-b6a39300-a124-11eb-948f-3c7844f777e3.png)

![image27](https://user-images.githubusercontent.com/10989147/115206371-b99e8380-a124-11eb-890c-82f7646a9369.png)

![image28](https://user-images.githubusercontent.com/10989147/115206382-bc997400-a124-11eb-8bce-81aa1df48997.png)

![image29](https://user-images.githubusercontent.com/10989147/115206394-befbce00-a124-11eb-84cf-30abd7f16871.png)

![image30](https://user-images.githubusercontent.com/10989147/115206404-c15e2800-a124-11eb-8dd9-258b7c385858.png)

![image31](https://user-images.githubusercontent.com/10989147/115206410-c3c08200-a124-11eb-81f5-5f981031152e.png)

![image32](https://user-images.githubusercontent.com/10989147/115206428-c8853600-a124-11eb-84a3-fbd40d811a69.png)

![image33](https://user-images.githubusercontent.com/10989147/115206453-cf13ad80-a124-11eb-84ee-1a8f13113dc1.png)

![image34](https://user-images.githubusercontent.com/10989147/115206556-ec487c00-a124-11eb-975a-213028ff57ea.png)

![image35](https://user-images.githubusercontent.com/10989147/115206567-eeaad600-a124-11eb-8c2b-3893eeb72408.png)

![image36](https://user-images.githubusercontent.com/10989147/115206579-f10d3000-a124-11eb-9d23-b076c5100d7b.png)

![image37](https://user-images.githubusercontent.com/10989147/115206594-f4082080-a124-11eb-9396-ec28c4606f81.png)

![image38](https://user-images.githubusercontent.com/10989147/115206605-f66a7a80-a124-11eb-91b3-cd97249cb5fa.png)

**Comment by afa28** [comment]
Kumpulan Tema OpenSID :
![klasik](https://user-images.githubusercontent.com/57283157/121661714-1429df80-cad7-11eb-93f5-dfe0d42ffd68.png)

**Comment by agungsugiarto** [comment]
Panduan untuk v21.08 
- https://github.com/OpenSID/OpenSID/issues/2321
![image](https://user-images.githubusercontent.com/10989147/128465036-73b863ab-90d7-459e-85dd-b43e3fc3b0f0.png)
