### ISSUE TITLE
Untuk panduan v21.11

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4500]

**Comment by andifahruddinakas** [comment]
#### Penambahan Fitur
- [x] 1. [#4366](https://github.com/OpenSID/OpenSID/issues/4366) RSS Feeds artikel sekarang berisi tanggal unggah artikel.
- [x] 2. [#4440](https://github.com/OpenSID/OpenSID/issues/4440) Perbaiki tampilan hasil analisis di web, supaya indikator ditampilkan per master analisis.
- [x] 3. [#4446](https://github.com/OpenSID/OpenSID/issues/4446) Perbaiki surat keterangan nikah sesuai dg KEPDIRJEN BIMAS ISLAM NO. 473 TAHUN 2020.
- [x] 4. [#4322](https://github.com/OpenSID/OpenSID/issues/4322) Sediakan notifikasi telegram ke pengguna admin / operator. (https://github.com/OpenSID/OpenSID/wiki/Bot-Notifikasi-Telegram)
- [x] 5. [#4376](https://github.com/OpenSID/OpenSID/issues/4376) Pencarian dan kategori produk pada web lapak.
- [x] 6. [#3844](https://github.com/OpenSID/OpenSID/issues/3844) Perjelas keterangan data kependudukan wilayah pada halaman website desa.
- [x] 7. [#3404](https://github.com/OpenSID/OpenSID/issues/3404) Penyesuaian Istilah Baru tentng COVID-19.
- [ ] 8. [#4402](https://github.com/OpenSID/OpenSID/issues/4402) Tampilkan data Pembangunan di halaman WEB.
- [ ] 9. [#4404](https://github.com/OpenSID/OpenSID/issues/4404) Kaitkan indikator/pertanyaan analisis dengan data kependudukan.
- [x] 10. [#4352](https://github.com/OpenSID/OpenSID/issues/4352) Sediakan kolom input ID BDT di menu Tambah Rumah Tangga Baru.
- [ ] 11. Ubah No. KK Sementara dari 0 menjadi 16 digit diawali 0, dengan format 0[kode-desa-10-digit][nomor-urut-5-digit]
- [ ] 12. Sediakan bisa pecah seluruh anggota keluarga status mati/hilang/pindah dan masukkan ke keluarga baru.

**Comment by andifahruddinakas** [comment]
Analisis Web : 
![web analisis  1](https://user-images.githubusercontent.com/57283157/139571510-109e42b2-3f1b-4951-89a7-a98077db5ad6.png)
![web analisis  2](https://user-images.githubusercontent.com/57283157/139571512-e970afaf-7655-4530-bad4-23a6f9f71482.png)
![web analisis  3](https://user-images.githubusercontent.com/57283157/139571513-44b97ed9-8233-4357-b019-f490b606d1b9.png)

**Comment by andifahruddinakas** [comment]
Lapak Web : 
![lapak 1](https://user-images.githubusercontent.com/57283157/139571646-c72baeae-1a2d-4270-af61-b231545e7e45.png)
![lapak 2](https://user-images.githubusercontent.com/57283157/139571649-deb70e2c-c360-45d2-a179-ebdf9f34f676.png)
![lapak 3](https://user-images.githubusercontent.com/57283157/139571651-fd18b032-9bdb-4f45-8995-e211a3e895f3.png)
![lapak 3](https://user-images.githubusercontent.com/57283157/139572140-d926c0fa-be49-4131-bcb8-d8161c29a402.png)

**Comment by andifahruddinakas** [comment]
Telegram : 
![telegram 1](https://user-images.githubusercontent.com/57283157/139571705-f99006b6-5443-48ff-9505-96f69e45e55b.png)

**Comment by andifahruddinakas** [comment]
Covid19 Web : 
![covid19 web](https://user-images.githubusercontent.com/57283157/139571785-cab25378-58ee-4cb8-9263-21111ccc847a.png)
![covid19 web 2](https://user-images.githubusercontent.com/57283157/139571844-dcb78594-c88f-46cb-8176-621e545e360a.png)

**Comment by andifahruddinakas** [comment]
Data Wilayah Web : 
![data wilayah web](https://user-images.githubusercontent.com/57283157/139571912-05712fb8-30d7-4322-a4bf-dc2eb5b8939d.png)

**Comment by andifahruddinakas** [comment]
QRCode : 
![qrcode](https://user-images.githubusercontent.com/57283157/139646702-e6c3f20c-bc51-466f-b4b7-01992bb90e91.png)
![qrcode1](https://user-images.githubusercontent.com/57283157/139646988-cc4ed327-e0aa-482d-9501-91c435043560.png)
![photo_2021-11-10_17-41-29](https://user-images.githubusercontent.com/57283157/141651880-d037fb62-a5c5-4664-948f-364d307d47f3.jpg)
