### ISSUE TITLE
Cetak dokumen TTE dalam bentuk pdf

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/OpenSID#4854]
Dokumen yang telah ditandangani berformat pdf dan dapat diunduh sesuai ketentuan BSrE pada uji proses TTE. 

-----------------------------------------------------
Pada prinsipnya document yang ingin diterapkan TTE akan di post ke API local yang disebut Esign Client Service 
dimana system ini akan di dapat dari BSrE yang akan di install ke server local berikut keterangan lebih jelasnya : 

**Apa kekurangan yg ingin diatasi?**
Menambahkan Fungsi Generate TTE pada setiap document bertanda tangan dengan format (.pdf)

**Basic alur dari BSrE** 
kita harus jga menerapkan yang namanya Esign Client Service  (Esign Client Service merupakan aplikasi yang berfungsi sebagai Gateway antara Sistem Informasi milik pengguna layanan BSrE dengan Esign Cloud yang berada pada jaringan BSrE.)

Normalnya alurnya seperti dibawah ini : 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/59082428/177356604-0540f8fb-d9a8-47f3-8aaa-5bd467340d39.png">

Esign Client Service dapat digunakan oleh lebih dari satu Sistem/Aplikasi. Setiap Sistem/Aplikasi yang akan menerapkan tanda tangan elektronik dapat menggunakan REST API yang disediakan oleh Esign Client Service telah diinstal pada jaringan lokal server pengguna (infomasi ini didapat dari documentasi penerapan BSrE.

**Cara Kerjanya TTE :** 
Document yang ingin di TTE akan di upload ke server local melalui API  Esign Client Service yang sudah terconnection lalu akan ter generate pdf baru output dari API  Esign Client Service tersebut dengan Pdf yang sudah ter TTE . 
- lalu ada 4 jenis TTE 
 1. Pdf TTE tanpa visual (artinya pdf telah ter TTE namun tidak nampak secara visual) 
 2. Pdf dengan Images (artinya pdf telah ter TTE akan ada tambahan images yang ingin kta terapkan didalam pdf tersebut)
 3. Pdf dengan Qrcode (artinya pdf telah ter TTE dan dengan qrcode tambahan )
 4. Pdf dengan Tag cordinat (artinya pdf telah ter TTE dapat digunakan pada dokumen yang terlebih dahulu
diberi Tag berupa karakter unik

**Cara Memeriksa Document telah ter TTE**
1.  dengan ngcheck ke url kominfo pusat https://tte.kominfo.go.id/verifyPDF
2. Bisa juga dengan APi verifikasi melalui API Esign Client Service 

**Untuk melakukan hal diatas tentu saja kita harus mendapat persetujuan dari BSrE**
Hal ini terkait dengan syarat :
- #4835 
- Syarat server terpenuhi Minimal : ini digunakan untuk API Esign Client Service 
  - Sistem Operasi : Centos 7
  - RAM : 8 GB
  - Processor : 4 Core
  - HDD : 50 GB
  - Port : 80, 443, 22

**Comment by vickyrolanda** [comment]
> Dokumen yang telah ditandangani berformat pdf dan dapat diunduh sesuai ketentuan BSrE pada uji proses TTE.

**Comment by apidong** [comment]
hal - hal yang perlu dilakukan untuk penerapan tte :

- [ ] buatkan sebuah pengaturan untuk mengaktifkan / non aktifkan modul tte.  issue : https://github.com/OpenSID/OpenSID/issues/4835
- [ ] tambahkan pengaturan untuk koordinat qrcode TTE pada masing2 template surat.
- [ ] tambahkan pengaturan untuk di kirim ke kecataman (opendk)  pada masing2 template surat. 
- [ ] buat migrasi untuk membuat group untuk rule kepala desa dan sekdes.  issue : https://github.com/OpenSID/OpenSID/issues/5403
- [ ] sesuaikan alur pemeriksaan surat sesuai dengan pengaturan modul tte. issue : https://github.com/OpenSID/OpenSID/issues/5270 
- [ ] sesuaikan alur pemeriksaan surat pada layanan mandiri. issue : https://github.com/OpenSID/OpenSID/issues/5271
- [ ] Cetak dokumen TTE dalam bentuk pdf dan hasilnya tersimpan di dalam server.
- [ ] Sediakan inputan pengisian passphrase yang hanya bisa dilakukan oleh kepala desa. 
- [ ] Buat notifikasi penanganan exception dalam proses TTE
- [ ] buat sebuah backend yang menghubungkan opensid dengan server API TTE.

**Comment by apidong** [comment]
@vickyrolanda mohon di periksa, apakah ada yang kurang atau perlu diperbaiki.

**Comment by eddieridwan** [comment]
@yogiperdana @apidong kalau sudah dibuatkan issue untuk masing2 tugas, sebaiknya issue ini ditutup saja.
