### ISSUE TITLE
Panduan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#4939]
- [x] 1. [#4803](https://github.com/OpenSID/OpenSID/issues/4803) Default no telpon pengguna saat buat surat di layanan mandiri.
- [x] 2. [#4767](https://github.com/OpenSID/OpenSID/issues/4767) Hanya tampilkan daftar Perangkat Desa yang aktif saat pilih Kepala Desa di Identitas Desa.
- [x] 3. [#4730](https://github.com/OpenSID/OpenSID/issues/4730) Urutan Nama Dusun Belum ter-Urut tampil pada menu cetak/rekap laporan Fitur Pendataan Vaksin.
- [x] 4. [#4800](https://github.com/OpenSID/OpenSID/issues/4800) Penambahan autocomplete pada pencarian daftar penerima vaksin.
- [x] 5. [#4589](https://github.com/OpenSID/OpenSID/issues/4589) Pencarian berdasarkan tagIdCard pada suplemen dan program bantuan.
- [x] 6. [#4814](https://github.com/OpenSID/OpenSID/issues/4814) Informasi halaman home untuk jumlah data kelompok hanya untuk yang ketua nya masih hidup.
- [x] 7. [#4726](https://github.com/OpenSID/OpenSID/issues/4726) Penambahan jenis file unggah dokumen (jpeg, png dan pdf) pada pendataan vaksin dan perbaiki tampilan lihat dokumen.
- [x] 8. [#4831](https://github.com/OpenSID/OpenSID/issues/4831) Mengganti tema klasik dengan tema esensi.
- [x] 9. [#4816](https://github.com/OpenSID/OpenSID/issues/4816) Penambahan penyaringan status pada modul kelompok/lembaga.
- [ ] 10. [#4784](https://github.com/OpenSID/OpenSID/issues/4784) Penambahan halaman pada modul Kelompok/Lembaga > Anggota.
- [ ] 11. [#4608](https://github.com/OpenSID/OpenSID/issues/4608) Unggah dokumen kependudukan menggunakan kamera.
- [ ] 12. [#1032](https://github.com/OpenSID/OpenSID/issues/1032) Penambahan informasi jumlah dan rincian data ganda saat melakukan impor data penduduk.
- [x] 13. [#4750](https://github.com/OpenSID/OpenSID/issues/4750) Pilihan Tahun di Statistik Bantuan.
- [x] 14. [#4707](https://github.com/OpenSID/OpenSID/issues/4707) Penambahan captcha untuk form pengaduan.
- [x] 15. [#4706](https://github.com/OpenSID/OpenSID/issues/4706) Penambahan notifikasi telegram setiap ada pengaduan.
- [ ] 16. [#2859](https://github.com/OpenSID/OpenSID/issues/2859) Penambahan kelengkapan data kematian saat ubah status dasar menjadi mati.
- [x] 17. [#4644](https://github.com/OpenSID/OpenSID/issues/4644) Penambahan halaman publikasi data warga yang sudah divaksin.
- [x] 18. [#4924](https://github.com/OpenSID/OpenSID/issues/4924) Pindahkan impor data rumah tangga ke modul Rumah Tangga.
- [x] 19. [#4806](https://github.com/OpenSID/OpenSID/issues/4806) Penambahan Lupa/reset PIN kirim melalui email.
- [x] 20. [#4643](https://github.com/OpenSID/OpenSID/issues/4643) Penambahan import data penerima vaksin.

**Comment by FirlianiF** [comment]
![Capture](https://user-images.githubusercontent.com/30171560/156058736-f6d9707f-e5f9-40bb-baae-746fd94ec67b.PNG)
![2](https://user-images.githubusercontent.com/30171560/156058744-8e54bdcb-3ab5-4157-aa72-fd25c2f10f5a.PNG)

**Comment by FirlianiF** [comment]
![3](https://user-images.githubusercontent.com/30171560/156059008-aa519b2d-fefd-493d-9d76-e7af5a36f3ac.PNG)

**Comment by FirlianiF** [comment]
![vv](https://user-images.githubusercontent.com/30171560/156061227-fc890882-85c0-4e6b-a3ae-5044d3c59b10.PNG)

**Comment by FirlianiF** [comment]
![151694809-d2e39762-dda3-4921-aff5-5b5c78c0735e](https://user-images.githubusercontent.com/30171560/156063653-0474ec7b-b9ee-4a43-9eb0-ff353eeba3eb.png)

**Comment by FirlianiF** [comment]
![TEMA](https://user-images.githubusercontent.com/30171560/156067889-1899ef53-1ac8-4d16-9ab2-acf1f73b31ed.PNG)

**Comment by FirlianiF** [comment]
![kelompok - Copy (2)](https://user-images.githubusercontent.com/30171560/156069241-7754d9e0-fe0f-4c55-88b2-ff71f668dd41.PNG)
![kelompok - Copy](https://user-images.githubusercontent.com/30171560/156069248-923926ec-0b05-446f-ace7-a6c5417cb198.PNG)
![kelompok](https://user-images.githubusercontent.com/30171560/156069249-e29df5ba-856a-42a1-b3b9-6af1d06c4c15.PNG)

**Comment by FirlianiF** [comment]
![adu](https://user-images.githubusercontent.com/30171560/156070577-30948698-dcb5-46ff-96a2-0c518304a991.PNG)

**Comment by FirlianiF** [comment]
![1](https://user-images.githubusercontent.com/30171560/156071732-2fa0ad98-878e-49e5-9a33-6b52eaea4ce3.PNG)

**Comment by FirlianiF** [comment]
![impor - Copy](https://user-images.githubusercontent.com/30171560/156073336-dec13721-24a2-48f4-84e2-14fba648a58f.PNG)
![ok](https://user-images.githubusercontent.com/30171560/156073342-4e83f0f0-88df-4b18-b4ca-8bfd3c2172e3.PNG)

**Comment by FirlianiF** [comment]
![modal](https://user-images.githubusercontent.com/30171560/156076047-b03c6e2b-3fba-4af6-8f91-7033f022105b.PNG)
![modal - Copy](https://user-images.githubusercontent.com/30171560/156076052-34c104ba-f945-4ba4-b8dc-10fd0d229cf1.PNG)

**Comment by FirlianiF** [comment]
![pilih pin](https://user-images.githubusercontent.com/30171560/156077857-f9834139-9524-4e72-a514-c0b4cb721cec.PNG)
![pin email](https://user-images.githubusercontent.com/30171560/156077861-d353b52a-8d82-4584-9f24-d812e53915d1.PNG)
![emailna](https://user-images.githubusercontent.com/30171560/156077865-2981ff4d-9033-4b1d-91b8-c74508d6e215.PNG)

**Comment by FirlianiF** [comment]
![vaksin](https://user-images.githubusercontent.com/30171560/156079532-eebcc612-85f0-4edc-b03c-3a606d021fb5.PNG)
![2](https://user-images.githubusercontent.com/30171560/156079537-eb9070fd-e499-4800-a1f4-2196855c159a.PNG)

**Comment by FirlianiF** [comment]
![ok](https://user-images.githubusercontent.com/30171560/156082512-d4821bd7-ed34-42b1-b38e-b6d78b71f9d5.PNG)
![vaksin excel](https://user-images.githubusercontent.com/30171560/156082517-06a802be-1e97-45c0-bc43-041058666904.PNG)
![catatan excel](https://user-images.githubusercontent.com/30171560/156082519-ef1c0a80-7e86-464d-a2c2-5663f3ca1ae2.PNG)
![modal](https://user-images.githubusercontent.com/30171560/156082522-475cb37d-589e-4e10-bdda-846bf0265f09.PNG)

**Comment by FirlianiF** [comment]
![modal](https://user-images.githubusercontent.com/30171560/156083016-3a1b9e26-6023-4f0a-bb58-571415d95efd.PNG)

![modal - Copy](https://user-images.githubusercontent.com/30171560/156083021-87059ea4-4546-435a-9988-a83e71c05255.PNG)

**Comment by FirlianiF** [comment]
![tahun](https://user-images.githubusercontent.com/30171560/156084879-5aa9500f-7db4-42b0-90b3-296f180a94c4.png)
