### ISSUE TITLE
Perencanaan & Laporan Pengerjaan Test Plan Minggu 2

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5384]
OpenSID
- [x] [TinyMCE] Pengaturan Default Font #5305
- [x] [TinyMCE] Ridirect Ke Arsip / Daftar Surat Setelah Cetak Surat #5306
- [x] Bug/error: Impor data penduduk dengan No KK < 16 digit #5314
- [x] Bug/error: Error saat tambah hari libur yg sama #5321
- [x] Bug/error: Perbarui surat rtf #5323
- [x] Bug/error: Album galeri pada web yang berisi lebih dari 10 foto, link pada halaman berikutnya tidak ditemukan #5339
- [x] Bug/error: Tombol Batal Pada Popup Pengaturan Pelanggan Tidak Berfungsi #5341
- [x] Bug/error: fungsi perbarui surat tidak berjalan dengan semestinya.#5344
- [x] Bug/error: error saat mencetak surat domisili non warga[#5351](https://github.com/OpenSID/OpenSID/issues/5351)
- [x] Permintaan fitur: tambahkan popup untuk melihat foto pada galeri dengan jelas #5371
- [x] Permintaan fitur: buat nama album menjadi wajib di isi #5372
- [x] Bug/error: gambar gagal disimpan tapi alert nya berhasil disimpan #5373
- [x] Bug/error: perbaiki validasi saat input token pelanggan dan perbaiki notif yang tidak muncul[#5374]
- [x] Bug/error: perbaiki validasi saat input token pelanggan dan perbaiki notif yang tidak muncul #5374
- [x] Bug/error: Typo pada alert saat menambah hari libur dengan tanggal yang sama #5377
- [x] Bug/error: error saat cetak PDF di menu Cetak Surat saat hanya ada a.n[#5379]
- [x] Bug/error: error saat cetak surat menggunakan tinyMce #5380
