### ISSUE TITLE
Perencanaan Pengerjaan Test Plan Minggu 3

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/OpenSID#5385]
OpenSID
- [ ] [Peta] Tampilan Keterangan Gambar di Peta Bisa Urut ke Bawah [#107](https://github.com/OpenSID/OpenSID/issues/5402)
- [ ] Bug/error: Nomor surat pada verifikasi qr Code semua mengikuti format nomor surat pada pengaturan Aplikasi[#5358](https://github.com/OpenSID/OpenSID/issues/5358)
- [ ] Bug/error: Statistik > Laporan bulanan untuk jumlah Keluarga masih tidak singkron dengan data wilayah[#5383](https://github.com/OpenSID/OpenSID/issues/5383)
- [ ] Bug/error: Realisasi APBDes Tidak sama antara OpenSID dan Siskeudes[#5359](https://github.com/OpenSID/OpenSID/issues/5359)
- [ ] Bug/error: Edit bulanan ibu hamil pada menu stunting tidak dapat dilakukan, atau error.[#5366](https://github.com/OpenSID/OpenSID/issues/5366)
- [ ] Bug/error: Data Stunting Pemantauan bulanan anak 0-2 tahun tidak bisa diisikan umur lebih dari 12 bulan[#5357](https://github.com/OpenSID/OpenSID/issues/5357)
- [ ] Bug/error: Tampilkan Error saat terjadi kegagalan dalam proses backup inkremental[#5381](https://github.com/OpenSID/OpenSID/issues/5381)
- [ ] Bug/error: Ketika scan kehadiran yg muncul bukan perangkat tersebut[#5346](https://github.com/OpenSID/OpenSID/issues/5346)

OpenDK
- [ ] Sediakan sinkronisasi fasilitas PAUD dari Opensid[#295](https://github.com/OpenSID/OpenDK/issues/295)
- [ ] Terapkan sentry untuk menangkap log [#329](https://github.com/OpenSID/OpenDK/issues/329)
- [ ] Penggunaan cmd Queue:listen merepotkan pengguna[#282](https://github.com/OpenSID/OpenDK/issues/282)
- [ ] Tampilkan berita desa yang berurutan berdasarkan tanggal penerbitan artikel[#360](https://github.com/OpenSID/OpenDK/issues/360)
- [ ] Sediakan Widget tambahan kebutuhan lain yang fleksibel,misal untuk embed halaman facebook atau lain nya[#293](https://github.com/OpenSID/OpenDK/issues/293)
- [ ] Sediakan data suplemen untuk opendk[#267](https://github.com/OpenSID/OpenDK/issues/267)
- [ ] Sediakan Fitur Backup/Restore Database dan Folder Storage[#417](https://github.com/OpenSID/OpenDK/issues/417)
- [ ] Sediakan fitur untuk pembuatan pendaftaran kerjasama dengan opendesa[#435](https://github.com/OpenSID/OpenDK/issues/435)
- [ ] module keluarga error [#450](https://github.com/OpenSID/OpenDK/issues/450)
