### ISSUE TITLE
Optimalisasi Fitur Surat Keluar OpenSID

### ISSUE THREAD

**Issue by PemdesAdiwarno** [OpenSID/OpenSID#6809]
### Apa kekurangan yg ingin diatasi?

![image](https://github.com/OpenSID/OpenSID/assets/124587672/33d8291e-26b4-45b9-a90a-5dd11ca2320f)
difitur surat keluar akan terisi apabila desa melakukan upload surat di fitur ini.
seluruh surat yang di buat di menu cetak surat, saat ini hanya untuk surat permohonan dari warga.
Apabila desa membuat surat keluar cth. undangan/surat pengantar ke instansi lain belum dapat otomatis masuk di fitur surat keluar.

### Jelaskan solusi yg diinginkan

![Surat Keluar OpenSID](https://github.com/OpenSID/OpenSID/assets/124587672/bbb63891-1cab-492e-820c-055da374925e)
Disediakan fitur cetak surat keluar dinas desa. sehingga pengisian di surat keluar akan otomatis masuk ke arsip surat keluar desa.

### Apakah ada alternatif lain

1. TTE OpenSID akan bermanfaat lebih optimal, (penandatanganan tidak memakai e-office/aplikasi bsign)
2. Surat keluar akan teragenda secara lebih rapi dan teratur.
3. Dapat diaplikasikan untuk mengirim surat secara elektronik melalui aplikasi (OpenDK/OpenKAB) sehingga terbentuk ekosistem surat elektronik melalui platform Opendesa.
4. Desa sering mencetak surat dinas keluar.

### Untuk versi OpenSID mana

23.09-premium

### Informasi tambahan

Semoga dapat di aplikasikan

**Comment by andifahruddinakas** [comment]
ini mas @vickyrolanda

**Comment by luxmant354** [comment]
up, sangat dibutuhkan

**Comment by andifahruddinakas** [comment]
Pecahan Issue :
- [ ] Pengaturan surat (https://github.com/OpenSID/OpenSID/issues/7762)
- [ ] Arsip surat (https://github.com/OpenSID/OpenSID/issues/7764)
- [ ] Cetak surat (https://github.com/OpenSID/OpenSID/issues/7763)
- [ ] Template Surat (https://github.com/OpenSID/OpenSID/issues/7765)
