### ISSUE TITLE
Hak akses tidak sesuai dengan yang diberikan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7047]
- [x] Pengaturan Peta https://github.com/OpenSID/OpenSID/issues/7045

- [x] Kelompok/Lembaga https://github.com/OpenSID/OpenSID/issues/7046

- [x] Pengurus https://github.com/OpenSID/OpenSID/issues/7048

- [x] Inventaris https://github.com/OpenSID/OpenSID/issues/7050

- [x] Menu https://github.com/OpenSID/OpenSID/issues/7051

- [x] Buku Administrasi Desa https://github.com/OpenSID/OpenSID/issues/7068

- [x] Klasifikasi https://github.com/OpenSID/premium/issues/2813

- [x] Pengaturan Grup https://github.com/OpenSID/premium/issues/2830

- [x] Log Penduduk https://github.com/OpenSID/premium/issues/2831
