### ISSUE TITLE
Sesuaikan surat bawaan tinymce

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7310]
Surat TinyMCE yang perlu disesuaikan disesuaikan sbb : 
- [x] Surat Biodata Penduduk #7328
- [x] Surat Keterangan Beda Identitas #7329
- [x] Surat Keterangan Beda Identitas KIS #7330
- [x] Surat Keterangan Bepergian
- [x] Surat Keterangan Domisili #7331
- [x] Surat Keterangan Domisili Non Warga (Hapus surat ini dan sesuaikan pada Surat Keterangan Domisi bisa menggunakan penduduk luar dea)
- [x] Surat Keterangan Domisili Usaha #7332
- [x] Surat Keterangan Izin Orang Tua Suami Istri https://github.com/OpenSID/OpenSID/issues/7316
- [x] Surat Keterangan JAMKESOS https://github.com/OpenSID/OpenSID/issues/7346
- [x] Surat Keterangan Jual Beli https://github.com/OpenSID/OpenSID/issues/7298
- [x] Surat Keterangan Kelahiran https://github.com/OpenSID/OpenSID/issues/7322
- [x] Surat Keterangan Kematian https://github.com/OpenSID/OpenSID/issues/7300
- [x] Surat Keterangan Kepemilikan Kendaraan https://github.com/OpenSID/OpenSID/issues/7297
- [x] Surat Keterangan Kepemilikan Tanah https://github.com/OpenSID/OpenSID/issues/7296
- [x] Surat Keterangan KTP dalam Proses
- [x] Surat Keterangan Kurang Mampu
- [x] Surat Keterangan Lahir Mati #7333
- [x] Surat Keterangan Nikah
- [x] Surat Keterangan Penduduk
- [x] Surat Keterangan Pengantar
- [x] Surat Keterangan Pengantar Rujuk/Cerai https://github.com/OpenSID/OpenSID/issues/7295
- [x] Surat Keterangan Penghasilan Ibu https://github.com/OpenSID/OpenSID/issues/7324
- [x] Surat Keterangan Penghasilan Orang Tua
- [x] Surat Keterangan Pergi Kawin
- [x] Surat Keterangan Pindah Penduduk https://github.com/OpenSID/OpenSID/issues/7326
- [x] Surat Keterangan Untuk Nikah Warga Non Muslim https://github.com/OpenSID/OpenSID/issues/7293
- [x] Surat Keterangan Usaha
- [x] Surat Keterangan Wali Hakim
- [x] Surat Kuasa #7334
- [x] Surat Pengantar Izin Keramaian
- [x] Surat Pengantar Laporan Kehilangan
- [x] Surat Pengantar Permohonan Penerbitan Buku Pas Lintas
- [x] Surat Pengantar Surat Keterangan Catatan Kepolisian
- [x] Surat Perintah Perjalanan Dinas https://github.com/OpenSID/OpenSID/issues/7291
- [x] Surat Permohonan Akta Lahir #7335
- [x] Surat Permohonan Cerai
- [x] Surat Permohonan Duplikat Kelahiran https://github.com/OpenSID/OpenSID/issues/7290
- [x] Surat Permohonan Duplikat Surat Nikah #7336
- [x] Surat Permohonan Kartu Keluarga
- [x] Surat Permohonan Perubahan Kartu Keluarga https://github.com/OpenSID/OpenSID/issues/7289
- [x] Surat Pernyataan Belum Memiliki Akta Lahir
- [x] Surat Pernyataan Penguasaan Fisik Bidang Tanah (SPORADIK) https://github.com/OpenSID/OpenSID/issues/7288
- [x] Surat Raw TinyMCE #7343
- [x] Surat Keterangan Penghasilan Ayah https://github.com/OpenSID/OpenSID/issues/7325
