### ISSUE TITLE
Konversi Lampiran Ke TinyMCE

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7349]
Perlu dikonversi ke tinymce : 
- [x] 1. F-1.01 https://github.com/OpenSID/OpenSID/issues/7301
- [ ] 2. F-1.02 https://github.com/OpenSID/OpenSID/issues/7352
- [ ] 3. F-1.03 https://github.com/OpenSID/OpenSID/issues/7353
- [ ] 4. F-1.06 https://github.com/OpenSID/OpenSID/issues/7319
- [ ] 5. F-1.08 https://github.com/OpenSID/OpenSID/issues/7354
- [ ] 6. F-1.15 https://github.com/OpenSID/OpenSID/issues/7355
- [ ] 7. F-1.16 https://github.com/OpenSID/OpenSID/issues/7356
- [ ] 8. F-1.25 https://github.com/OpenSID/OpenSID/issues/7357
- [ ] 9. F-1.27 https://github.com/OpenSID/OpenSID/issues/7358
- [ ] 10. F-2.01 https://github.com/OpenSID/OpenSID/issues/7284
- [ ] 11. F-2.12 https://github.com/OpenSID/OpenSID/issues/7351
- [x] 12. N-1 https://github.com/OpenSID/premium/pull/3076
- [x] 13. N-2 https://github.com/OpenSID/premium/pull/3077
- [x] 14. N-4 https://github.com/OpenSID/premium/pull/3078
- [x] 15. N-5 https://github.com/OpenSID/OpenSID/issues/7269
- [x] 16. N-6 https://github.com/OpenSID/premium/pull/3080
- [x] 17. SPS https://github.com/OpenSID/premium/pull/3072
- [x] 18. SWN https://github.com/OpenSID/premium/pull/3071

**Comment by andifahruddinakas** [comment]
Memerlukan beberapa pengaturan : 
- [x] pengaturan border kotak pada tabel https://github.com/OpenSID/OpenSID/issues/7279
- [ ] pengaturan maksimal jumlah kotak
