### ISSUE TITLE
Penyesuaian pratinjau pengaturan template surat TinyMCE

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7360]
Pratinjau Surat TinyMCE yang perlu disesuaikan disesuaikan sbb : 
- [x] Surat Biodata Penduduk #7370
- [x] Surat Keterangan Beda Identitas #7371
- [x] Surat Keterangan Beda Identitas KIS
- [x] Surat Keterangan Bepergian #7372
- [x] Surat Keterangan Domisili #7373
- [x] Surat Keterangan Domisili Usaha #7374
- [x] Surat Keterangan Izin Orang Tua Suami Istri #7375
- [x] Surat Keterangan JAMKESOS #7376
- [x] Surat Keterangan Jual Beli #7377
- [x] Surat Keterangan Kelahiran #7378
- [x] Surat Keterangan Kematian #7379
- [x] Surat Keterangan Kepemilikan Kendaraan #7380
- [x] Surat Keterangan Kepemilikan Tanah #7381
- [x] Surat Keterangan KTP dalam Proses #7382
- [x] Surat Keterangan Kurang Mampu #7383
- [x] Surat Keterangan Lahir Mati #7384
- [x] Surat Keterangan Nikah #7386
- [x] Surat Keterangan Penduduk #7387
- [x] Surat Keterangan Pengantar #7388
- [x] Surat Keterangan Pengantar Rujuk/Cerai #7389
- [x] Surat Keterangan Penghasilan Ibu #7390
- [x] Surat Keterangan Penghasilan Orang Tua #7391
- [x] Surat Keterangan Pergi Kawin #7392
- [x] Surat Keterangan Pindah Penduduk #7393
- [x] Surat Keterangan Untuk Nikah Warga Non Muslim #7394
- [x] Surat Keterangan Usaha 
- [x] Surat Keterangan Wali Hakim
- [x] Surat Kuasa
- [x] Surat Pengantar Izin Keramaian
- [x] Surat Pengantar Laporan Kehilangan
- [x] Surat Pengantar Permohonan Penerbitan Buku Pas Lintas
- [x] Surat Pengantar Surat Keterangan Catatan Kepolisian
- [x] Surat Perintah Perjalanan Dinas
- [x] Surat Permohonan Akta Lahir
- [ ] Surat Permohonan Cerai
- [ ] Surat Permohonan Duplikat Kelahiran
- [x] Surat Permohonan Duplikat Surat Nikah
- [x] Surat Permohonan Kartu Keluarga
- [x] Surat Permohonan Perubahan Kartu Keluarga
- [x] Surat Pernyataan Belum Memiliki Akta Lahir #7397
- [x] Surat Pernyataan Penguasaan Fisik Bidang Tanah (SPORADIK) #7396
- [x] Surat Keterangan Penghasilan Ayah #7395

**Comment by andifahruddinakas** [comment]
- [ ] Surat Perintah Perjalanan Dinas
`ERROR - 2023-12-02 01:29:01 --> Severity: error --> Exception: Could not parse '02 Desember 2023': Failed to parse time string (02 Desember 2023) at position 0 (0): Unexpected character D:\PROJECT OPENDESA\OpenSID\vendor\nesbot\carbon\src\Carbon\Traits\Creator.php 198
`
