### ISSUE TITLE
Seragamkan fungsi tombol batal pada modal

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7411]
Terkait pembahasan issue https://github.com/OpenSID/OpenSID/issues/6765

Modul : 
- [ ] Wilayah Administratif https://github.com/OpenSID/OpenSID/issues/7412
- [ ] Pemerintah desa https://github.com/OpenSID/OpenSID/issues/7413
- [ ] Lembaga Desa https://github.com/OpenSID/OpenSID/issues/7414
- [ ] Penduduk https://github.com/OpenSID/OpenSID/issues/7418
- [ ] Rumah Tangga https://github.com/OpenSID/OpenSID/issues/7419
- [ ] Statistik Kependuduk https://github.com/OpenSID/OpenSID/issues/7420
- [ ] Suplemen https://github.com/OpenSID/OpenSID/issues/7467
- [ ] Pengaturan Surat https://github.com/OpenSID/OpenSID/issues/7468
- [ ] Statistik Penduduk https://github.com/OpenSID/OpenSID/issues/7469
- [ ] Laporan Bulanan https://github.com/OpenSID/OpenSID/issues/7470
- [ ] Informasi Publik https://github.com/OpenSID/OpenSID/issues/7471
- [ ] Inventaris https://github.com/OpenSID/OpenSID/issues/7472
- [ ] Buku Peraturan di Desa https://github.com/OpenSID/OpenSID/issues/7473
- [ ] Lainnya

**Comment by andifahruddinakas** [comment]
Solusi : 
- Ganti ejaan menjadi **batal**
- Fungsinya hanya untuk membatalkan perubahan.
- Buat helper tombol batal agar konsisten.

**Comment by andifahruddinakas** [comment]
<img width="250" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/464e7264-5938-4794-af41-011695839e22">

<img width="254" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/3fcbb91c-91bf-4c0b-8976-9e4ea25487f0">
