### ISSUE TITLE
Penyesuaian Lampiran Surat Permohonan Administrasi Kependudukan

### ISSUE THREAD

**Issue by yugaeko** [OpenSID/OpenSID#7796]
**Latar Belakang**
Sesuai dengan Peraturan Menteri Dalam Negeri Nomor 109 Tahun 2019 tentang Formulir Dan Buku Yang Digunakan Dalam Administrasi Kependudukan, ada beberapa lampiran default di OPENSID yang masih kurang sesuai dengan format yang diminta oleh permendagri tersebut.

**Masalah**
Secara data, hampir semua sudah cocok, hanya saja beda ditampilan, jumlah halaman dan tata letak. sehingga output dari OpenSID yang ada saat ini tidak bisa kami gunakan sebagai persyaratan pengajuan adminduk di DUKCAPIL KABUPATEN MALANG

**Harapan**
Harapannya, lampiran-lampiran yang dari OPENSID disesuaikan dengan permendagri yang ada.

**Tantangan**
Bisa jadi antara daerah satu dengan daerah yang lain penerapannya di lapangan berbeda-beda. Tapi karena ini proyek nasional, bukan proyek kedaerahan, mestinya kita ikut ke aturan pusat UU/Peraturan Menteri atau lainnya, bukan ke Peraturan Daerah masing-masing

**CONTOH DETAIL**
Berikut detail beberapa perbedaan untuk saat ini : (VERSI 24.03)

**1. Form F101**

Output OpenSID
- 2 Halaman
- Tidak ada kop
![image](https://github.com/OpenSID/OpenSID/assets/9125101/c4221ad6-12d6-4033-a952-9882b18bff3e)

Permendagri
- 3 halaman
- ada kop
![image](https://github.com/OpenSID/OpenSID/assets/9125101/91e30296-7c3a-42df-a3aa-8f726318b977)

Kenapa harus di sesuaikan? karena untuk pelayanan online (di kabupaten malang contohnya) harus upload form f101 sebanyak 3 halaman, maka jika itu hanya 2 halaman, kita tidak bisa pakai fitur ini.

2. Form F201

Output OpenSID
- 1 halaman
![image](https://github.com/OpenSID/OpenSID/assets/9125101/4309daa9-892a-4d9f-8b4a-0392e31bb41e)

Permendagri
- 4 halaman
![image](https://github.com/OpenSID/OpenSID/assets/9125101/f8a7a4c4-2aca-463c-973e-3bf375e61910)
![image](https://github.com/OpenSID/OpenSID/assets/9125101/8bd13b52-eb44-4bcc-89ca-ebcf50e18bbe)

3. Form F103

Output OpenSID
- 1 Halaman - Portrait
![image](https://github.com/OpenSID/OpenSID/assets/9125101/29b770ae-a392-4f19-894b-94bcbbe408b5)

Permendagri
- 2 halaman - Landscape
![image](https://github.com/OpenSID/OpenSID/assets/9125101/6ec586f1-99f1-44a3-bc05-9a6b27bf113a)

itu tadi beberapa perbedaan yang ada untuk formulir yang bisa jadi sering digunakan, barangkali semua lampiran bisa disesuaikan dengan permendagri yang ada juga akan lebih baik lagi..

Terima kasih banyak.

**Comment by eddieridwan** [comment]
Usahakan memperoleh koding yg sudah dibuat oleh pelapor. @andifahruddinakas

**Comment by yugaeko** [comment]
file apa perlu kami kirim di sini pak?

**Comment by andifahruddinakas** [comment]
Refrensi https://peraturan.bpk.go.id/Details/138575/permendagri-no-109-tahun-2019

[Permendagri 109 Tahun 2019.pdf](https://github.com/user-attachments/files/20582064/Permendagri.109.Tahun.2019.pdf)

Lampiran Surat yg perlu disesuaikan : 

- [ ] Lampiran F-1.01 (Formatnya ada di halaman 25 - 27, ada 3 halaman) https://github.com/OpenSID/OpenSID/issues/9606
- [ ] Lampiran F-2.01 (Saat ini hanya 1 - 2 halaman sesuai data yang dipilih, untuk menghemat kertas, karena tidak semua diisi) https://github.com/OpenSID/OpenSID/issues/9655
- [ ] Lampiran F-1.03 (Formatnya ada di halaman 32 - 33, ada 2 halaman) https://github.com/OpenSID/OpenSID/issues/9607

**Comment by yugaeko** [comment]
Lampiran F-2.01 (Saat ini hanya 1 - 2 halaman sesuai data yang dipilih, untuk menghemat kertas, karena tidak semua diisi)

*jika memang referensinya hemat kertas, kan tinggal operatornya nanti yang cetak data yang terisi saja

format ajuan DUKCAPIL KABUPATEN MALANG harus upload 4 halaman, tidak bisa kirim pengajuan jika hanya 1 atau 2 halaman

![Image](https://github.com/user-attachments/assets/6cab3806-3dcb-4bcc-ada6-d13522061b79)

**Comment by yugaeko** [comment]
maaf baru muncul edaran baru terkait efisiensi, hampir semua form berubah menjadi 1 halaman dan ukuran A4, jadi kami rasa permintaan ini tidak jadi berlaku. mohon maaf, terima kasih.

[SURAT PEMBERITAHUAN OPERATOR DESAKU TUNTAS (1).pdf](https://github.com/user-attachments/files/21458407/SURAT.PEMBERITAHUAN.OPERATOR.DESAKU.TUNTAS.1.pdf)
