### ISSUE TITLE
Konversi Layanan Mandiri Web

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7826]
Modul : 
- [x] #8046
- [x] https://github.com/OpenSID/OpenSID/issues/8048
- [x] https://github.com/OpenSID/OpenSID/issues/8053
- [x] https://github.com/OpenSID/OpenSID/issues/8049
- [x] https://github.com/OpenSID/OpenSID/issues/8050
- [x] https://github.com/OpenSID/OpenSID/issues/8056
- [x] https://github.com/OpenSID/OpenSID/issues/8057
- [x] https://github.com/OpenSID/OpenSID/issues/8055
- [x] https://github.com/OpenSID/OpenSID/issues/8052
- [x] https://github.com/OpenSID/OpenSID/issues/8054
