### ISSUE TITLE
Konversi Modul Analisis menggunakan ORM dan Blade

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8535]
![image](https://github.com/user-attachments/assets/7454c019-bb80-4165-9ae6-41ad27100224)

catatan : 
- [ ] Untuk modul analisis terapkan konsep modul sama seperti anjungan
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] pindahkan ke controller baru agar tidak bengkak
- [ ] sesuaikan router jika ada perubahan
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru

**Comment by andifahruddinakas** [comment]
Bagian-bagian menu analisis:
- [x] https://github.com/OpenSID/OpenSID/issues/8536
![image](https://github.com/user-attachments/assets/16ba06dd-790d-49a0-b120-09b093e4fea6)

- [x] https://github.com/OpenSID/OpenSID/issues/8537
![image](https://github.com/user-attachments/assets/fd392c9f-5bde-478b-9ce3-331055ce7f4d)
![image](https://github.com/user-attachments/assets/7e1ce23c-4cda-4038-9698-cbda76ae3a2c)

- [x] https://github.com/OpenSID/OpenSID/issues/8538
![image](https://github.com/user-attachments/assets/18f47add-99dc-420b-871b-84917a624310)

- [x] https://github.com/OpenSID/OpenSID/issues/8539
![image](https://github.com/user-attachments/assets/e109cb53-7245-4737-b9a8-cc7ee679c37f)

- [x] https://github.com/OpenSID/OpenSID/issues/8540
![image](https://github.com/user-attachments/assets/75329238-e0ac-47f1-a69b-a1b55b3c8c0b)

- [x] https://github.com/OpenSID/OpenSID/issues/8541
![image](https://github.com/user-attachments/assets/f066f3a0-37b6-4d72-b0e8-89a56a694959)

- [x] https://github.com/OpenSID/OpenSID/issues/8542
![image](https://github.com/user-attachments/assets/f7e0a9aa-8fc3-4249-9909-6044189504a7)

- [ ] https://github.com/OpenSID/OpenSID/issues/8543
![image](https://github.com/user-attachments/assets/8cc2e4bb-0397-46d7-a367-03859ebbc639)

**Comment by andifahruddinakas** [comment]
mas @pandigresik, @habibie11, untuk modul analisi arahkan PR ke branch https://github.com/OpenSID/premium/tree/modul-analisis

**Comment by andifahruddinakas** [comment]
- [x] https://github.com/OpenSID/OpenSID/issues/8551
![image](https://github.com/user-attachments/assets/41e5f04d-8ea6-4140-9837-cb1f874cf4dc)
