### ISSUE TITLE
Konversi Modul Statistik Kependudukan

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8592]
Submodul : 

- [x] https://github.com/OpenSID/OpenSID/issues/8218
- [x] https://github.com/OpenSID/OpenSID/issues/8219
- [x] https://github.com/OpenSID/OpenSID/issues/8220
- [x] https://github.com/OpenSID/OpenSID/issues/8221
