### ISSUE TITLE
Konversi Halaman Web / Tema

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8645]
- [ ] Halaman Utama, terdiri dari template, layout (full, right, left)
  - [x] #8646
  - [x] #8647
  - [x] #8706
  - [x] #8708
  - [x] #8709
  - [x] #8721
  - [x] #8722
  - [x] #8710
  - [x] #8686
  - [x] #8711
  - [x] #8695
  - [x] #8696
  - [x] #8712
  - [x] #8687
  - [x] #8713
  - [x] #8707
  - [x] #8723
  - [x] #8725
  - [x] #8724
  - [x] #8736
  - [x] #8737
  - [x] #8738
  - [x] #8751
  - [x] Vaksi (Akan Dihapus)
  - [x] #8752
  - [x] #8755
  
catatan : 
- [ ] hapus query lama
- [ ] hapus view lama dan gunakan blade (gunakan komponen blade; @if, @forrech, @select, dll)
- [ ] pindahkan ke controller baru agar tidak bengkak
- [ ] sesuaikan router jika ada perubahan
- [ ] gunakan button non flat, untuk membedakan dengan modul yg sudah dikonversi
- [ ] sesuaikan kondisi terkait tte
- [ ] sederhanakan proses/fungsi yang rumit
- [ ] gunakan pengecekan hak akses yang baru
- [ ] hapus penggunaan view, gunakan orm dan relasi
- [ ] pengerjaan meliputi tema bawaan (esensi dan natra)
- [ ] gunakan api untuk menampilkan data yang dibutuhkan pada halaman ini. GUnakan format yang sama dengan OpenKab https://github.com/OpenSID/OpenKab/pull/79/files
- [ ] pisahkan di masing2 kontroller (fweb)

**Comment by andifahruddinakas** [comment]
Gunakan dan arahkan ke branch https://github.com/OpenSID/premium/pull/4211 untuk pengerjaan issue ini.
