### ISSUE TITLE
Gunakan Framework Laravel 

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8658]
Bagian dari konversi : 

- [ ] Alihkan semua core dari CI 3.x.x menggunakan Laravel 10.x.x
- [ ] Hapus semua package yang tidak digunakan untuk pengembangan di Laravel 10.x.x
- [ ] Tambahkan package untuk pengembangan di Laravel 10.x.x

**Comment by tandiyo** [comment]
Kami siap berkontribusi mas kalau bisa langsung ke Laravel 11.x.x

**Comment by agung2001** [comment]
proses konversi ini tidak mudah, karena dari stuktur dan cara kerja 
ke-2 framework CodeIgniter dan Laravel sangatlah berbeda
sebagai contoh pembuatan model : 
- CodeIgniter : https://codeigniter.com/userguide3/general/models.html
- Laravel : https://laravel.com/docs/11.x/eloquent#introduction

@andifahruddinakas mungkin untuk proses awal kita bisa lakukan breakdown terlebih dahulu 
apa saja yang harus dilakukan dengan memecah issue ini kedalam sub issues

untuk catatan, proses migrasi juga sebaiknya di install khusus pada sub-direktori misal `laravel-app` 
lalu meredirect fitur2 yang sudah di migrasi ke subdirectory tersebut melalui menu di admin
dengan begitu kita bisa meminimalisir kesalahan dan fatal error

**Comment by andifahruddinakas** [comment]
> proses konversi ini tidak mudah, karena dari stuktur dan cara kerja ke-2 framework CodeIgniter dan Laravel sangatlah berbeda sebagai contoh pembuatan model :
> 
> * CodeIgniter : https://codeigniter.com/userguide3/general/models.html
> * Laravel : https://laravel.com/docs/11.x/eloquent#introduction
> 
> @andifahruddinakas mungkin untuk proses awal kita bisa lakukan breakdown terlebih dahulu apa saja yang harus dilakukan dengan memecah issue ini kedalam sub issues
> 
> untuk catatan, proses migrasi juga sebaiknya di install khusus pada sub-direktori misal `laravel-app` lalu meredirect fitur2 yang sudah di migrasi ke subdirectory tersebut melalui menu di admin dengan begitu kita bisa meminimalisir kesalahan dan fatal error

Sudah dilakukan secara bertahap menggunakan komponen laravel illuminate yang berjalan dengan core ci3. Tinggal melakukan pemindahan secara utuh menggunakan core laravel 10.x dengan pertimbangan versi php dan komponen illuminate yg digunakan.

**Comment by agung2001** [comment]
baik mas jadi pemindahan dilakukan secara langsung pada root directory dengan menggunakan komponen [illuminate](https://github.com/OpenSID/premium/blob/c71fe8cc273ee167231273b760ae736097924241/composer.json#L19-L42)
tapi apakah betul pemindahan langsung dapat dilakukan? saya masih melihat banyak modul belum dimigrasi secara penuh

## Models
[models](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/models) masih menggunakan model CodeIgniter sebagai contoh : 
- https://github.com/OpenSID/premium/blob/c8ce6ddd7fe7afb4bbc3f6f0e34889b52d62e220/donjo-app/models/Acak_model.php#L41 `extends MY_Model` --> `extends CI_Model`
- https://github.com/OpenSID/premium/blob/c8ce6ddd7fe7afb4bbc3f6f0e34889b52d62e220/donjo-app/models/Agenda_model.php#L40 `extends MY_Model` --> `extends CI_Model`
- dst

## Views
[views](https://github.com/OpenSID/premium/blob/3f64b2e4dbd845f7eeb9fbe62517c4be477e8e82/donjo-app/views) masih belum menggunakan blade engine : 
- https://github.com/OpenSID/premium/blob/ee159051c9abb5513282e875bb77da0cd0c02752/donjo-app/views/footer.php
- https://github.com/OpenSID/premium/blob/16555440eda1342bbf68b0391f7a86cd44930a00/donjo-app/views/header.php
- dst

## Controller
[controller](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/controllers) masih menggunakan basis CodeIgniter sebagai contoh : 
- https://github.com/OpenSID/premium/blob/48185adb919a6a50ad63f6df9453a5d9e46d5d5b/donjo-app/controllers/Admin_pembangunan.php#L48 `extends Admin_Controller` --> `extends MY_Controller` --> `extends CI_Controller`
- https://github.com/OpenSID/premium/blob/99bb8a8d982c766800a757b9c77cbfdf95c11b66/donjo-app/controllers/AnggotaKeluarga.php#L67 `extends Admin_Controller` --> `extends MY_Controller` --> `extends CI_Controller`
- dst

agar para kontributor lain bisa memahami dan lebih jelas mungkin mas @andifahruddinakas bisa lebih mendetail kan step2 apa saja yang perlu dikerjakan sehingga output nya bisa lebih terstruktur dan terukur mas. bagaimana mas @vickyrolanda mungkin ada ide atau saran?

**Comment by andifahruddinakas** [comment]
> baik mas jadi pemindahan dilakukan secara langsung pada root directory dengan menggunakan komponen [illuminate](https://github.com/OpenSID/premium/blob/c71fe8cc273ee167231273b760ae736097924241/composer.json#L19-L42) tapi apakah betul pemindahan langsung dapat dilakukan? saya masih melihat banyak modul belum dimigrasi secara penuh
> 
> ## Models
> [models](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/models) masih menggunakan model CodeIgniter sebagai contoh :
> 
> * https://github.com/OpenSID/premium/blob/c8ce6ddd7fe7afb4bbc3f6f0e34889b52d62e220/donjo-app/models/Acak_model.php#L41 `extends MY_Model` --> `extends CI_Model`
> * https://github.com/OpenSID/premium/blob/c8ce6ddd7fe7afb4bbc3f6f0e34889b52d62e220/donjo-app/models/Agenda_model.php#L40 `extends MY_Model` --> `extends CI_Model`
> * dst
> 
> ## Views
> [views](https://github.com/OpenSID/premium/blob/3f64b2e4dbd845f7eeb9fbe62517c4be477e8e82/donjo-app/views) masih belum menggunakan blade engine :
> 
> * https://github.com/OpenSID/premium/blob/ee159051c9abb5513282e875bb77da0cd0c02752/donjo-app/views/footer.php
> * https://github.com/OpenSID/premium/blob/16555440eda1342bbf68b0391f7a86cd44930a00/donjo-app/views/header.php
> * dst
> 
> ## Controller
> [controller](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/controllers) masih menggunakan basis CodeIgniter sebagai contoh :
> 
> * https://github.com/OpenSID/premium/blob/48185adb919a6a50ad63f6df9453a5d9e46d5d5b/donjo-app/controllers/Admin_pembangunan.php#L48 `extends Admin_Controller` --> `extends MY_Controller` --> `extends CI_Controller`
> * https://github.com/OpenSID/premium/blob/99bb8a8d982c766800a757b9c77cbfdf95c11b66/donjo-app/controllers/AnggotaKeluarga.php#L67 `extends Admin_Controller` --> `extends MY_Controller` --> `extends CI_Controller`
> * dst
> 
> agar para kontributor lain bisa memahami dan lebih jelas mungkin mas @andifahruddinakas bisa lebih mendetail kan step2 apa saja yang perlu dikerjakan sehingga output nya bisa lebih terstruktur dan terukur mas. bagaimana mas @vickyrolanda mungkin ada ide atau saran?

Untuk bagian admin sudah sepenuhnya dipindahkan, adapun seperti modul vaksi belum/tidak dipindahkan karena kedepannya modul tsb akan dihapus. Karena hal tsb view footer dan header belum sepenuhnya terhapus krn masih digunakan pada modul tsb.

Untuk kasus halaman depan / tema bulan ini target selesai dikonversi, sehingga model lama seperti agenda_model akan dihapus seiring konversi tsb.

Sisanya dilakukan pengecekan untuk menyesuaikan bagian yang belum dipindahkan melalui PR https://github.com/OpenSID/premium/pull/4210

Untuk core controller akan dibuat kembali menyesuaikan dengan yang ada di laravel, tentunya dengan tidak membuang fungsi yang sudah ada.

Untuk pemindahan ini nantinya tidak langsung dirilis pada bulan yang sama, karena masih perlu dicek modul2 yang ada apakah sudah berjalan normal seperti sebelumnya.

**Comment by agung2001** [comment]
baik, berarti kalau kita simpulkan berikut adalah checklist yang masih perlu kita lakukan saat melakukan migrasi :

1. **Modul Admin**
   - [x] Pindahkan seluruh bagian admin.
   - [ ] Hapus modul vaksin. https://github.com/OpenSID/OpenSID/issues/8633
   - [ ] Hapus footer dan header [views](https://github.com/OpenSID/premium/blob/3f64b2e4dbd845f7eeb9fbe62517c4be477e8e82/donjo-app/views), setelah migrasi selesai **Belum ada Issue/Pull Request**

2. **Halaman Depan / Tema** https://github.com/OpenSID/OpenSID/issues/8645
   - [ ] Selesaikan konversi halaman depan atau tema bulan ini. https://github.com/OpenSID/premium/pull/4211
      - [ ] Hapus [model](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/models) lama seperti (`agenda_model`, dll) setelah konversi selesai **Belum ada Issue/Pull Request**
   - [x] Lakukan pengecekan menyeluruh untuk menyesuaikan bagian yang belum dipindahkan melalui PR https://github.com/OpenSID/premium/pull/4210

3. **Core Controller**
   - [ ] Buat ulang *core controller* agar sesuai dengan standar di Laravel. **Belum ada Issue/Pull Request**

5. **Pengujian Akhir dan Perilisan**
   - [ ] Cek semua modul untuk memastikan mereka berjalan normal seperti pada versi sebelumnya. **Belum ada Issue/Pull Request**
   - [ ] Tunda perilisan pemindahan ini sampai pengecekan lengkap telah selesai dilakukan. **Belum ada Issue/Pull Request**

#### Catatan
mungkin bisa di check lagi mas @andifahruddinakas siapa tau ada yang salah related issue nya
dan juga ini mungkin beberapa pekerjaan yg **Belum ada Issue/Pull Request** 
bisa kita buat atau beri catatan kalau sudah ada supaya teman2 yg lain bisa mengikuti 😁👍

**Comment by andifahruddinakas** [comment]
> baik, berarti kalau kita simpulkan berikut adalah checklist yang masih perlu kita lakukan saat melakukan migrasi :
> 
> 1. **Modul Admin**
>    
>    * [x]  Pindahkan seluruh bagian admin.
>    * [ ]  Hapus modul vaksin.
>    * [ ]  Hapus footer dan header [views](https://github.com/OpenSID/premium/blob/3f64b2e4dbd845f7eeb9fbe62517c4be477e8e82/donjo-app/views), setelah migrasi selesai **Belum ada Issue/Pull Request**
> 2. **Halaman Depan / Tema**
>    
>    * [ ]  Selesaikan konversi halaman depan atau tema bulan ini. [Konversi Tema premium#4211](https://github.com/OpenSID/premium/pull/4211)
>      
>      * [ ]  Hapus [model](https://github.com/OpenSID/premium/blob/568c43cab6db7a15d73f416b81d7382b9f116bac/donjo-app/models) lama seperti (`agenda_model`, dll) setelah konversi selesai **Belum ada Issue/Pull Request**
>    * [x]  Lakukan pengecekan menyeluruh untuk menyesuaikan bagian yang belum dipindahkan melalui PR [Sisa konversi premium#4210](https://github.com/OpenSID/premium/pull/4210)
> 3. **Core Controller**
>    
>    * [ ]  Buat ulang _core controller_ agar sesuai dengan standar di Laravel. **Belum ada Issue/Pull Request**
> 4. **Pengujian Akhir dan Perilisan**
>    
>    * [ ]  Cek semua modul untuk memastikan mereka berjalan normal seperti pada versi sebelumnya. **Belum ada Issue/Pull Request**
>    * [ ]  Tunda perilisan pemindahan ini sampai pengecekan lengkap telah selesai dilakukan. **Belum ada Issue/Pull Request**
> 
> #### Catatan
> mungkin bisa di check lagi mas @andifahruddinakas siapa tau ada yang salah related issue nya dan juga ini mungkin beberapa pekerjaan yg **Belum ada Issue/Pull Request** bisa kita buat atau beri catatan kalau sudah ada supaya teman2 yg lain bisa mengikuti 😁👍

Vaksin dan terkait view ci3 (pada admin sisa itu yg menggunakannya) : https://github.com/OpenSID/OpenSID/issues/8633

Untuk bulan ini fokus utamanya dibagian konversi tema, untuk pemindahan ke core laravel ditargetkan bulan depan. Untuk issue berlabel epic merupa issue utama, namun didalamnya terdapat issue lanjutan untuk memecah pengerjaan yang lebih kecil. Contoh : https://github.com/OpenSID/OpenSID/issues/8645

Untuk pemindahan core laravel bisa beri masukan di issue ini, biar nanti dijabarkan lagi untuk dikerjakan.
