### ISSUE TITLE
Gunakan Enum Untuk Data Statis

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#8659]
![image](https://github.com/user-attachments/assets/eb1eeb39-0c5a-46f1-97d2-d9765c88e375)

Untuk mengurangi jumlah data yang banyak dimana data merupakan data statis, maka perlu dilakukan efesiensi penggunaan tabel pada database dengan mengalihkan penggunaan tabel pada data statis menggunakan enums. Beberapa sudah menggunakan enums namun belum secara keseluruhan. Tabel yang perlu disesuaikan pada semua modul sbb:

- [ ] **Analisis**
  - [ ] analisis_ref_state
  - [ ] analisis_ref_subjek

- [x] **Keuangan** (Dihapus di Rilis v2412.0.0, karena masih tahap penyesuaian database, namun untuk hasil konversi sudah menggunakan enums)
  - [x] keuangan_manual_*
  - [x] keuangan_ref_*
  - [x] keuangan_ta_*
  
  

- [ ] **Pertanahan**
   - [ ] ref_asal_tanah_kas

- [ ] **Dokumen**
   - [ ] ref_dokumen

- [ ] **Penduduk**
  - [ ] ref_penduduk_bahasa
  - [x] ref_penduduk_hamil
  - [x] ref_penduduk_bidang
  - [x] ref_penduduk_kursus
  - [x] ref_penduduk_suku
  - [ ] ref_persil_kelas
  - [ ] ref_persil_mutasi
  - [ ] ref_peruntukan_tanah_kas
  - [ ] ref_pindah
  - [ ] ref_status_covid (x)
  - [x] tweb_cacat
  - [x] tweb_cara_kb
  - [x] tweb_golongan_darah (https://github.com/OpenSID/OpenSID/issues/9915)
  - [x] tweb_keluarga_sejahtera
  - [x] tweb_penduduk_agama (https://github.com/OpenSID/OpenSID/issues/9914)
  - [ ] tweb_penduduk_asuransi
  - [x] tweb_penduduk_hubungan
  - [x] tweb_penduduk_kawin
  - [x] tweb_penduduk_pekerjaan
  - [x] tweb_penduduk_pendidikan
  - [x] tweb_penduduk_pendidikan_kk
  - [x] tweb_penduduk_sex (https://github.com/OpenSID/OpenSID/issues/9912)
  - [x] tweb_penduduk_status
  - [x] tweb_penduduk_warganegara (https://github.com/OpenSID/OpenSID/issues/9913)
  - [x] tweb_rtm_hubungan
  - [x] tweb_sakit_menahun
  - [ ] tweb_status_dasar
  - [ ] tweb_status_ktp

**Comment by andifahruddinakas** [comment]
SOLUSI : 

- [ ] Buat Enum
- [ ] Sesuaikan Fungsi terkait
- [ ] Hapus tabel yg dikonversi lewat migrasi
- [ ] Sesuaikan install awal dengan kondisi tabel sudah dihapus
- [ ] Hapus model atau relasi terkait
- [ ] Beberapa modul yg langsung terpengaruh dan perlu disesuaikan seperti modul yg ada pada modul kependudukan, buku administrasi kependudukan.

<img width="926" height="462" alt="Image" src="https://github.com/user-attachments/assets/827b596e-4689-46f6-8eb2-6bb59463f628" />
